In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("dataset/Zone4_merged.csv")

In [4]:
data.head()

,Unnamed: 0.1,latitude,longitude,GHI (kWh/m2),NDBI,NDVI,BU,slope,surface_roughness,classes,...,tropospheric_HCHO_column_number_density_y,NO2_column_number_density_y,O3_column_number_density_y,SO2_column_number_density_y,ST_B10,NDWI,soil_moisture,LandUse,Amenity,SAVI
0,0,45.370087,9.206070,1418.0,0.005639,0.034569,-0.028930,89.999852,818.771878,6,...,0.000110,0.000133,0.142803,0.000028,293.821507,-0.245300,57.342589,railway,drinking_water,0.046529
1,1,45.490821,9.231402,1419.9,-0.052354,0.067374,-0.119728,89.989082,818.771878,6,...,0.000130,0.000147,0.142105,0.000048,297.174585,-0.209471,145.803903,residential,clock,0.092720
2,2,45.452014,9.106896,1415.2,-0.095350,0.144253,-0.239603,89.984559,818.771878,6,...,0.000118,0.000139,0.142889,0.000095,298.206827,-0.136116,73.553405,residential,cafe,0.326356
3,3,45.427490,9.099619,1405.7,-0.038965,0.085976,-0.124941,89.993095,818.771878,6,...,0.000111,0.000134,0.142269,0.000087,295.226314,-0.188627,73.553405,residential,cafe,0.203799
4,4,45.493516,9.168880,1406.0,-0.018685,0.049283,-0.067969,89.991435,818.771878,6,...,0.000127,0.000147,0.141959,0.000077,295.790287,-0.209471,137.647683,residential,bank,0.078630

In [5]:
data = data.rename(columns={'latitude': 'Latitude'})
data = data.rename(columns={'longitude': 'Longitude'})
data = data.rename(columns={'GHI (kWh/m2)': 'solar_radiation'})
data = data.rename(columns={'slope': 'Slope'})
data = data.rename(columns={'surface_roughness': 'Roughness'})
data = data.rename(columns={'ST_B10': 'LST'})
data = data.rename(columns={'soil_moisture': 'SMI'})
data = data.rename(columns={'LandUse': 'landuse'})

In [9]:
data.head()

,Unnamed: 0.1,Latitude,Longitude,solar_radiation,NDBI,NDVI,BU,Slope,Roughness,classes,...,tropospheric_HCHO_column_number_density_y,NO2_column_number_density_y,O3_column_number_density_y,SO2_column_number_density_y,LST,NDWI,SMI,landuse,Amenity,SAVI
0,0,45.370087,9.206070,1418.0,0.005639,0.034569,-0.028930,89.999852,818.771878,6,...,0.000110,0.000133,0.142803,0.000028,293.821507,-0.245300,57.342589,railway,drinking_water,0.046529
1,1,45.490821,9.231402,1419.9,-0.052354,0.067374,-0.119728,89.989082,818.771878,6,...,0.000130,0.000147,0.142105,0.000048,297.174585,-0.209471,145.803903,residential,clock,0.092720
2,2,45.452014,9.106896,1415.2,-0.095350,0.144253,-0.239603,89.984559,818.771878,6,...,0.000118,0.000139,0.142889,0.000095,298.206827,-0.136116,73.553405,residential,cafe,0.326356
3,3,45.427490,9.099619,1405.7,-0.038965,0.085976,-0.124941,89.993095,818.771878,6,...,0.000111,0.000134,0.142269,0.000087,295.226314,-0.188627,73.553405,residential,cafe,0.203799
4,4,45.493516,9.168880,1406.0,-0.018685,0.049283,-0.067969,89.991435,818.771878,6,...,0.000127,0.000147,0.141959,0.000077,295.790287,-0.209471,137.647683,residential,bank,0.078630

In [6]:
data["Zone"] = "zone4"

In [7]:
data.to_csv("merged_2023_z4.csv", index=False)